var hierarchy =
[
    [ "Allocator", "classrapidjson_1_1_allocator.html", null ],
    [ "GenericValue< Encoding, Allocator >::ArrayData", "struct_generic_value_1_1_array_data.html", null ],
    [ "ASCII< CharType >", "struct_a_s_c_i_i.html", null ],
    [ "attribute_iterator< Ch >", "classrapidxml_1_1attribute__iterator.html", null ],
    [ "xml_document< Ch >::attribute_name_pred", "structrapidxml_1_1xml__document_1_1attribute__name__pred.html", null ],
    [ "xml_document< Ch >::attribute_value_pred< Quote >", "structrapidxml_1_1xml__document_1_1attribute__value__pred.html", null ],
    [ "xml_document< Ch >::attribute_value_pure_pred< Quote >", "structrapidxml_1_1xml__document_1_1attribute__value__pure__pred.html", null ],
    [ "AutoUTF< CharType >", "struct_auto_u_t_f.html", null ],
    [ "AutoUTFInputStream< CharType, InputByteStream >", "class_auto_u_t_f_input_stream.html", null ],
    [ "AutoUTFOutputStream< CharType, OutputByteStream >", "class_auto_u_t_f_output_stream.html", null ],
    [ "BaseReaderHandler< Encoding, Derived >", "struct_base_reader_handler.html", null ],
    [ "BasicIStreamWrapper< StreamType >", "class_basic_i_stream_wrapper.html", null ],
    [ "BasicOStreamWrapper< StreamType >", "class_basic_o_stream_wrapper.html", null ],
    [ "BigInteger", "classinternal_1_1_big_integer.html", null ],
    [ "MemoryPoolAllocator< BaseAllocator >::ChunkHeader", "struct_memory_pool_allocator_1_1_chunk_header.html", null ],
    [ "GenericDocument< Encoding, Allocator, StackAllocator >::ClearStackOnExit", "struct_generic_document_1_1_clear_stack_on_exit.html", null ],
    [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ClearStackOnExit", "struct_generic_reader_1_1_clear_stack_on_exit.html", null ],
    [ "CrtAllocator", "class_crt_allocator.html", null ],
    [ "GenericValue< Encoding, Allocator >::Data", "union_generic_value_1_1_data.html", null ],
    [ "DecodedStream< SourceStream, Encoding >", "classinternal_1_1_decoded_stream.html", null ],
    [ "TPPLPartition::Diagonal", "struct_t_p_p_l_partition_1_1_diagonal.html", null ],
    [ "display_point", "class_i_m_d_f_1_1_o_p_e_n_i_n_g_1_1display__point.html", null ],
    [ "display_point", "class_i_m_d_f_1_1_u_n_i_t_1_1display__point.html", null ],
    [ "DiyFp", "structinternal_1_1_diy_fp.html", null ],
    [ "Double", "classinternal_1_1_double.html", null ],
    [ "TPPLPartition::DPState", "struct_t_p_p_l_partition_1_1_d_p_state.html", null ],
    [ "TPPLPartition::DPState2", "struct_t_p_p_l_partition_1_1_d_p_state2.html", null ],
    [ "EncodedInputStream< Encoding, InputByteStream >", "class_encoded_input_stream.html", null ],
    [ "EncodedInputStream< UTF8<>, MemoryStream >", "class_encoded_input_stream_3_01_u_t_f8_3_4_00_01_memory_stream_01_4.html", null ],
    [ "EncodedOutputStream< Encoding, OutputByteStream >", "class_encoded_output_stream.html", null ],
    [ "Encoding", "classrapidjson_1_1_encoding.html", null ],
    [ "exception", null, [
      [ "parse_error", "classrapidxml_1_1parse__error.html", null ]
    ] ],
    [ "FalseType", null, [
      [ "IsGenericValueImpl< T, Encoding, Allocator >", "structinternal_1_1_is_generic_value_impl.html", null ]
    ] ],
    [ "feature", "class_i_m_d_f_1_1_l_e_v_e_l_1_1feature.html", null ],
    [ "feature", "class_i_m_d_f_1_1_o_p_e_n_i_n_g_1_1feature.html", null ],
    [ "feature", "class_i_m_d_f_1_1_u_n_i_t_1_1feature.html", null ],
    [ "file< Ch >", "classrapidxml_1_1file.html", null ],
    [ "FileReadStream", "class_file_read_stream.html", null ],
    [ "FileWriteStream", "class_file_write_stream.html", null ],
    [ "GenericValue< Encoding, Allocator >::Flag", "struct_generic_value_1_1_flag.html", null ],
    [ "GenericRegex< Encoding, Allocator >::Frag", "structinternal_1_1_generic_regex_1_1_frag.html", null ],
    [ "GenericArray< Const, ValueT >", "class_generic_array.html", null ],
    [ "GenericInsituStringStream< Encoding >", "struct_generic_insitu_string_stream.html", null ],
    [ "GenericMember< Encoding, Allocator >", "struct_generic_member.html", null ],
    [ "GenericMemberIterator< Const, Encoding, Allocator >", "class_generic_member_iterator.html", null ],
    [ "GenericMemoryBuffer< Allocator >", "struct_generic_memory_buffer.html", null ],
    [ "GenericObject< Const, ValueT >", "class_generic_object.html", null ],
    [ "GenericPointer< ValueType, Allocator >", "class_generic_pointer.html", null ],
    [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >", "class_generic_reader.html", null ],
    [ "GenericRegex< Encoding, Allocator >", "classinternal_1_1_generic_regex.html", null ],
    [ "GenericRegexSearch< RegexType, Allocator >", "classinternal_1_1_generic_regex_search.html", null ],
    [ "GenericSchemaDocument< ValueT, Allocator >", "class_generic_schema_document.html", null ],
    [ "GenericStreamWrapper< InputStream, Encoding >", "class_generic_stream_wrapper.html", [
      [ "CursorStreamWrapper< InputStream, Encoding >", "class_cursor_stream_wrapper.html", null ]
    ] ],
    [ "GenericStringBuffer< Encoding, Allocator >", "class_generic_string_buffer.html", null ],
    [ "GenericStringRef< CharType >", "struct_generic_string_ref.html", null ],
    [ "GenericStringStream< Encoding >", "struct_generic_string_stream.html", null ],
    [ "GenericValue< Encoding, Allocator >", "class_generic_value.html", [
      [ "GenericDocument< Encoding, Allocator, StackAllocator >", "class_generic_document.html", null ]
    ] ],
    [ "GenericValue< EncodingType, Allocator >", "class_generic_value.html", null ],
    [ "GenericValue< EncodingType, AllocatorType >", "class_generic_value.html", null ],
    [ "GenericValue< EncodingType, StateAllocator >", "class_generic_value.html", null ],
    [ "GenericValue< SourceEncoding, StackAllocator >", "class_generic_value.html", null ],
    [ "geometry", "class_i_m_d_f_1_1_l_e_v_e_l_1_1geometry.html", null ],
    [ "geometry", "class_i_m_d_f_1_1_o_p_e_n_i_n_g_1_1geometry.html", null ],
    [ "geometry", "class_i_m_d_f_1_1_u_n_i_t_1_1geometry.html", null ],
    [ "Handler", "classrapidjson_1_1_handler.html", null ],
    [ "Hasher< Encoding, Allocator >", "classinternal_1_1_hasher.html", null ],
    [ "memory_pool< Ch >::header", "structrapidxml_1_1memory__pool_1_1header.html", null ],
    [ "GenericValue< Encoding, Allocator >::Number::I", "struct_generic_value_1_1_number_1_1_i.html", null ],
    [ "IC", "class_c_o_n_v_e_r_t_e_r_1_1_i_c.html", [
      [ "CellSpace", "class_c_o_n_v_e_r_t_e_r_1_1_cell_space.html", null ],
      [ "CellSpaceBoundary", "class_c_o_n_v_e_r_t_e_r_1_1_cell_space_boundary.html", null ],
      [ "Pos", "class_c_o_n_v_e_r_t_e_r_1_1_pos.html", null ],
      [ "State", "class_c_o_n_v_e_r_t_e_r_1_1_state.html", null ],
      [ "Transition", "class_c_o_n_v_e_r_t_e_r_1_1_transition.html", null ]
    ] ],
    [ "IGenericRemoteSchemaDocumentProvider< SchemaDocumentType >", "class_i_generic_remote_schema_document_provider.html", null ],
    [ "imaxdiv_t", "structimaxdiv__t.html", null ],
    [ "ISchemaStateFactory< SchemaType >", "classinternal_1_1_i_schema_state_factory.html", null ],
    [ "ISchemaStateFactory< SchemaDocumentType::SchemaType >", "classinternal_1_1_i_schema_state_factory.html", [
      [ "GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >", "class_generic_schema_validator.html", null ]
    ] ],
    [ "ISchemaValidator", "classinternal_1_1_i_schema_validator.html", [
      [ "GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >", "class_generic_schema_validator.html", null ]
    ] ],
    [ "IValidationErrorHandler< SchemaType >", "classinternal_1_1_i_validation_error_handler.html", null ],
    [ "IValidationErrorHandler< SchemaDocumentType::SchemaType >", "classinternal_1_1_i_validation_error_handler.html", [
      [ "GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >", "class_generic_schema_validator.html", null ]
    ] ],
    [ "level", "class_i_m_d_f_1_1_l_e_v_e_l_1_1level.html", null ],
    [ "Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level", "struct_writer_1_1_level.html", null ],
    [ "memory_pool< Ch >", "classrapidxml_1_1memory__pool.html", [
      [ "xml_document< Ch >", "classrapidxml_1_1xml__document.html", null ]
    ] ],
    [ "MemoryPoolAllocator< BaseAllocator >", "class_memory_pool_allocator.html", null ],
    [ "MemoryStream", "struct_memory_stream.html", null ],
    [ "TPPLPartition::MonotoneVertex", "struct_t_p_p_l_partition_1_1_monotone_vertex.html", null ],
    [ "node_iterator< Ch >", "classrapidxml_1_1node__iterator.html", null ],
    [ "xml_document< Ch >::node_name_pred", "structrapidxml_1_1xml__document_1_1node__name__pred.html", null ],
    [ "GenericValue< Encoding, Allocator >::Number", "union_generic_value_1_1_number.html", null ],
    [ "Hasher< Encoding, Allocator >::Number", "structinternal_1_1_hasher_1_1_number.html", null ],
    [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, backup, pushOnTake >", "class_generic_reader_1_1_number_stream.html", null ],
    [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >", "class_generic_reader_1_1_number_stream_3_01_input_stream_00_01false_00_01false_01_4.html", [
      [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, true, false >", "class_generic_reader_1_1_number_stream_3_01_input_stream_00_01true_00_01false_01_4.html", [
        [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, true, true >", "class_generic_reader_1_1_number_stream_3_01_input_stream_00_01true_00_01true_01_4.html", null ]
      ] ]
    ] ],
    [ "GenericValue< Encoding, Allocator >::ObjectData", "struct_generic_value_1_1_object_data.html", null ],
    [ "opening", "class_i_m_d_f_1_1_o_p_e_n_i_n_g_1_1opening.html", null ],
    [ "ParseResult", "struct_parse_result.html", null ],
    [ "TPPLPartition::PartitionVertex", "struct_t_p_p_l_partition_1_1_partition_vertex.html", null ],
    [ "Schema< SchemaDocumentType >::PatternProperty", "structinternal_1_1_schema_1_1_pattern_property.html", null ],
    [ "GenericPointer< ValueType, Allocator >::PercentEncodeStream< OutputStream >", "class_generic_pointer_1_1_percent_encode_stream.html", null ],
    [ "point", "class_i_m_d_f_1_1_o_p_e_n_i_n_g_1_1point.html", null ],
    [ "point", "class_i_m_d_f_1_1_l_e_v_e_l_1_1point.html", null ],
    [ "point", "class_i_m_d_f_1_1_u_n_i_t_1_1point.html", null ],
    [ "Point2D", "struct_c_o_n_v_e_r_t_e_r_1_1_point2_d.html", null ],
    [ "properties", "class_i_m_d_f_1_1_l_e_v_e_l_1_1properties.html", null ],
    [ "properties", "class_i_m_d_f_1_1_u_n_i_t_1_1properties.html", null ],
    [ "properties", "class_i_m_d_f_1_1_o_p_e_n_i_n_g_1_1properties.html", null ],
    [ "Schema< SchemaDocumentType >::Property", "structinternal_1_1_schema_1_1_property.html", null ],
    [ "GenericRegex< Encoding, Allocator >::Range", "structinternal_1_1_generic_regex_1_1_range.html", null ],
    [ "TPPLPartition::ScanLineEdge", "struct_t_p_p_l_partition_1_1_scan_line_edge.html", null ],
    [ "Schema< SchemaDocumentType >", "classinternal_1_1_schema.html", null ],
    [ "Schema< SchemaDocumentType >::SchemaArray", "structinternal_1_1_schema_1_1_schema_array.html", null ],
    [ "GenericSchemaDocument< ValueT, Allocator >::SchemaEntry", "struct_generic_schema_document_1_1_schema_entry.html", null ],
    [ "GenericSchemaDocument< ValueT, Allocator >::SchemaRefEntry", "struct_generic_schema_document_1_1_schema_ref_entry.html", null ],
    [ "SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >", "class_schema_validating_reader.html", null ],
    [ "SchemaValidationContext< SchemaDocumentType >", "structinternal_1_1_schema_validation_context.html", null ],
    [ "GenericValue< Encoding, Allocator >::ShortString", "struct_generic_value_1_1_short_string.html", null ],
    [ "Stack< Allocator >", "classinternal_1_1_stack.html", null ],
    [ "Stack< StackAllocator >", "classinternal_1_1_stack.html", null ],
    [ "Stack< StateAllocator >", "classinternal_1_1_stack.html", null ],
    [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >", "class_generic_reader_1_1_stack_stream.html", null ],
    [ "GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< char >", "class_generic_reader_1_1_stack_stream.html", null ],
    [ "GenericRegex< Encoding, Allocator >::State", "structinternal_1_1_generic_regex_1_1_state.html", null ],
    [ "Stream", "classrapidjson_1_1_stream.html", null ],
    [ "StreamLocalCopy< Stream, int >", "classinternal_1_1_stream_local_copy.html", null ],
    [ "StreamLocalCopy< Stream, 0 >", "classinternal_1_1_stream_local_copy_3_01_stream_00_010_01_4.html", null ],
    [ "StreamLocalCopy< Stream, 1 >", "classinternal_1_1_stream_local_copy_3_01_stream_00_011_01_4.html", null ],
    [ "StreamTraits< Stream >", "struct_stream_traits.html", null ],
    [ "StreamTraits< GenericInsituStringStream< Encoding > >", "struct_stream_traits_3_01_generic_insitu_string_stream_3_01_encoding_01_4_01_4.html", null ],
    [ "StreamTraits< GenericStringStream< Encoding > >", "struct_stream_traits_3_01_generic_string_stream_3_01_encoding_01_4_01_4.html", null ],
    [ "GenericValue< Encoding, Allocator >::String", "struct_generic_value_1_1_string.html", null ],
    [ "xml_document< Ch >::text_pred", "structrapidxml_1_1xml__document_1_1text__pred.html", null ],
    [ "xml_document< Ch >::text_pure_no_ws_pred", "structrapidxml_1_1xml__document_1_1text__pure__no__ws__pred.html", null ],
    [ "xml_document< Ch >::text_pure_with_ws_pred", "structrapidxml_1_1xml__document_1_1text__pure__with__ws__pred.html", null ],
    [ "GenericPointer< ValueType, Allocator >::Token", "struct_generic_pointer_1_1_token.html", null ],
    [ "TokenHelper< Stack, Ch >", "structinternal_1_1_token_helper.html", null ],
    [ "TokenHelper< Stack, char >", "structinternal_1_1_token_helper_3_01_stack_00_01char_01_4.html", null ],
    [ "TPPLPartition", "class_t_p_p_l_partition.html", null ],
    [ "TPPLPoint", "struct_t_p_p_l_point.html", null ],
    [ "TPPLPoly", "class_t_p_p_l_poly.html", null ],
    [ "Transcoder< SourceEncoding, TargetEncoding >", "struct_transcoder.html", null ],
    [ "Transcoder< Encoding, Encoding >", "struct_transcoder_3_01_encoding_00_01_encoding_01_4.html", null ],
    [ "Type", null, [
      [ "IsGenericValueImpl< T, typename Void< typename T::EncodingType >::Type, typename Void< typename T::AllocatorType >::Type >", "structinternal_1_1_is_generic_value_impl_3_01_t_00_01typename_01_void_3_01typename_01_t_1_1_enco3a51e9d8b4986f001b39e1e8edecb66a.html", null ]
    ] ],
    [ "Type", null, [
      [ "IsGenericValue< T >", "structinternal_1_1_is_generic_value.html", null ]
    ] ],
    [ "TypeHelper< ValueType, T >", "structinternal_1_1_type_helper.html", null ],
    [ "TypeHelper< ValueType, bool >", "structinternal_1_1_type_helper_3_01_value_type_00_01bool_01_4.html", null ],
    [ "TypeHelper< ValueType, const typename ValueType::Ch * >", "structinternal_1_1_type_helper_3_01_value_type_00_01const_01typename_01_value_type_1_1_ch_01_5_01_4.html", null ],
    [ "TypeHelper< ValueType, double >", "structinternal_1_1_type_helper_3_01_value_type_00_01double_01_4.html", null ],
    [ "TypeHelper< ValueType, float >", "structinternal_1_1_type_helper_3_01_value_type_00_01float_01_4.html", null ],
    [ "TypeHelper< ValueType, int >", "structinternal_1_1_type_helper_3_01_value_type_00_01int_01_4.html", null ],
    [ "TypeHelper< ValueType, int64_t >", "structinternal_1_1_type_helper_3_01_value_type_00_01int64__t_01_4.html", null ],
    [ "TypeHelper< ValueType, typename ValueType::Array >", "structinternal_1_1_type_helper_3_01_value_type_00_01typename_01_value_type_1_1_array_01_4.html", null ],
    [ "TypeHelper< ValueType, typename ValueType::ConstArray >", "structinternal_1_1_type_helper_3_01_value_type_00_01typename_01_value_type_1_1_const_array_01_4.html", null ],
    [ "TypeHelper< ValueType, typename ValueType::ConstObject >", "structinternal_1_1_type_helper_3_01_value_type_00_01typename_01_value_type_1_1_const_object_01_4.html", null ],
    [ "TypeHelper< ValueType, typename ValueType::Object >", "structinternal_1_1_type_helper_3_01_value_type_00_01typename_01_value_type_1_1_object_01_4.html", null ],
    [ "TypeHelper< ValueType, uint64_t >", "structinternal_1_1_type_helper_3_01_value_type_00_01uint64__t_01_4.html", null ],
    [ "TypeHelper< ValueType, unsigned >", "structinternal_1_1_type_helper_3_01_value_type_00_01unsigned_01_4.html", null ],
    [ "GenericValue< Encoding, Allocator >::Number::U", "struct_generic_value_1_1_number_1_1_u.html", null ],
    [ "Hasher< Encoding, Allocator >::Number::U", "unioninternal_1_1_hasher_1_1_number_1_1_u.html", null ],
    [ "unit", "class_i_m_d_f_1_1_u_n_i_t_1_1unit.html", null ],
    [ "UTF16< CharType >", "struct_u_t_f16.html", [
      [ "UTF16BE< CharType >", "struct_u_t_f16_b_e.html", null ],
      [ "UTF16LE< CharType >", "struct_u_t_f16_l_e.html", null ]
    ] ],
    [ "UTF32< CharType >", "struct_u_t_f32.html", [
      [ "UTF32BE< CharType >", "struct_u_t_f32_b_e.html", null ],
      [ "UTF32LE< CharType >", "struct_u_t_f32_l_e.html", null ]
    ] ],
    [ "UTF8< CharType >", "struct_u_t_f8.html", null ],
    [ "TPPLPartition::VertexSorter", "class_t_p_p_l_partition_1_1_vertex_sorter.html", null ],
    [ "xml_document< Ch >::whitespace_pred", "structrapidxml_1_1xml__document_1_1whitespace__pred.html", null ],
    [ "Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >", "class_writer.html", [
      [ "PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >", "class_pretty_writer.html", null ]
    ] ],
    [ "xml_base< Ch >", "classrapidxml_1_1xml__base.html", [
      [ "xml_attribute< Ch >", "classrapidxml_1_1xml__attribute.html", null ],
      [ "xml_node< Ch >", "classrapidxml_1_1xml__node.html", [
        [ "xml_document< Ch >", "classrapidxml_1_1xml__document.html", null ]
      ] ]
    ] ]
];